spring:
  r2dbc:
    username: aiaibot
    password: lena
    url: r2dbc:postgresql://localhost:5432/contact?ApplicationName=backend
  liquibase:
    user: aiaibot
    password: lena
    url: jdbc:postgresql://localhost:5432/contact?ApplicationName=backend