name: Build webapp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.6.1]

    steps:
      - uses: actions/checkout@v1

      - name: Node 16.6.1
        uses: actions/setup-node@v1
        with:
          node-version: 16.6.1
      
      - name: Install dependencies
        run: cd webapp && npm ci
          
      - name: Lint Action
        uses: wearerequired/lint-action@v1.10.0
        with:
          eslint: true
          eslint_dir: webapp/
          eslint_args: "--ext .js,.ts ."

      - name: Build webapp
        run: cd webapp && npm run build-ci